### ISSUE TITLE
Is it possible to make arc_color gradient?

### ISSUE THREAD

**Issue by imTefa** [bozapro/circular-slider-range#11]
Hi,
I need to make the arc_color  gradient color but I really don't know how
any help if it possible?

**Comment by bozapro** [comment]
Hi @imTefa ,

I tried with setting Shader to Paint (https://developer.android.com/reference/android/graphics/Paint#setShader(android.graphics.Shader)), but this doesn't work. Another way is with drawing shape bitmap on canvas, but this is more work. 
Feel free to provide PR if you have some ideas.

**Comment by imTefa** [comment]
Ok, thanks
I made a pull request with a change to make a gradient arc, I hope you look at it.
